# Generated by Django 6.0.1 on 2026-03-05 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_booking_refund_amount'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='unique_vendor_per_datetime',
        ),
        migrations.AddField(
            model_name='booking',
            name='advance_payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='balance_payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Advance Paid'), ('completed', 'Event Completed'), ('released', 'Paid to Vendor'), ('disputed', 'Disputed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.RemoveField(
            model_name='booking',
            name='event_completed',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='payout_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='razorpay_order_id',
        ),
    ]
