# Generated by Django 6.0.1 on 2026-03-23 04:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_passwordreset'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='phone',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (e.g. +919876543210). Up to 15 digits allowed.', regex='^\\+?\\d{9,15}$')]),
        ),
    ]
