# Generated by Django 6.0.1 on 2026-03-23 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_vendorportfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='advance_released',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='balance_released',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='payout_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
