# Generated by Django 6.0.1 on 2026-03-30 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_booking_advance_released_booking_balance_released_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='razorpay_payment_id',
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='food_type_selected',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='guest_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Is the vendor currently accepting new bookings?'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='is_caterer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendor',
            name='price_per_plate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='For Caterers: Price per person', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='base_price',
            field=models.DecimalField(decimal_places=2, help_text='General starting price', max_digits=10),
        ),
    ]
