# Generated by Django 6.0.1 on 2026-03-30 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_booking_razorpay_payment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='base_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='General starting price', max_digits=10, null=True),
        ),
    ]
