# Generated by Django 6.0.1 on 2026-04-06 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_vehicletype_booking_estimated_kilometers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='drop_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='pickup_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
